using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Gameboy_Emulator {
    static class Constants {

        // Autogenerated, find here: https://gbdev.io/gb-opcodes/optables/
        public static readonly InstructionReference[] instructions = {
            new InstructionReference("NOP ", "NOP", 0),		// 0x00
            new InstructionReference("LD BC, n16", "LD", 2),		// 0x01
            new InstructionReference("LD BC, A", "LD", 0),		// 0x02
            new InstructionReference("INC BC", "INC", 0),		// 0x03
            new InstructionReference("INC B", "INC", 0),		// 0x04
            new InstructionReference("DEC B", "DEC", 0),		// 0x05
            new InstructionReference("LD B, n8", "LD", 1),		// 0x06
            new InstructionReference("RLCA ", "RLCA", 0),		// 0x07
            new InstructionReference("LD a16, SP", "LD", 2),		// 0x08
            new InstructionReference("ADD HL, BC", "ADD", 0),		// 0x09
            new InstructionReference("LD A, BC", "LD", 0),		// 0x0A
            new InstructionReference("DEC BC", "DEC", 0),		// 0x0B
            new InstructionReference("INC C", "INC", 0),		// 0x0C
            new InstructionReference("DEC C", "DEC", 0),		// 0x0D
            new InstructionReference("LD C, n8", "LD", 1),		// 0x0E
            new InstructionReference("RRCA ", "RRCA", 0),		// 0x0F
            new InstructionReference("STOP n8", "STOP", 1),		// 0x10
            new InstructionReference("LD DE, n16", "LD", 2),		// 0x11
            new InstructionReference("LD DE, A", "LD", 0),		// 0x12
            new InstructionReference("INC DE", "INC", 0),		// 0x13
            new InstructionReference("INC D", "INC", 0),		// 0x14
            new InstructionReference("DEC D", "DEC", 0),		// 0x15
            new InstructionReference("LD D, n8", "LD", 1),		// 0x16
            new InstructionReference("RLA ", "RLA", 0),		// 0x17
            new InstructionReference("JR e8", "JR", 1),		// 0x18
            new InstructionReference("ADD HL, DE", "ADD", 0),		// 0x19
            new InstructionReference("LD A, DE", "LD", 0),		// 0x1A
            new InstructionReference("DEC DE", "DEC", 0),		// 0x1B
            new InstructionReference("INC E", "INC", 0),		// 0x1C
            new InstructionReference("DEC E", "DEC", 0),		// 0x1D
            new InstructionReference("LD E, n8", "LD", 1),		// 0x1E
            new InstructionReference("RRA ", "RRA", 0),		// 0x1F
            new InstructionReference("JR NZ, e8", "JR", 1),		// 0x20
            new InstructionReference("LD HL, n16", "LD", 2),		// 0x21
            new InstructionReference("LD HL, A", "LD", 0),		// 0x22
            new InstructionReference("INC HL", "INC", 0),		// 0x23
            new InstructionReference("INC H", "INC", 0),		// 0x24
            new InstructionReference("DEC H", "DEC", 0),		// 0x25
            new InstructionReference("LD H, n8", "LD", 1),		// 0x26
            new InstructionReference("DAA ", "DAA", 0),		// 0x27
            new InstructionReference("JR Z, e8", "JR", 1),		// 0x28
            new InstructionReference("ADD HL, HL", "ADD", 0),		// 0x29
            new InstructionReference("LD A, HL", "LD", 0),		// 0x2A
            new InstructionReference("DEC HL", "DEC", 0),		// 0x2B
            new InstructionReference("INC L", "INC", 0),		// 0x2C
            new InstructionReference("DEC L", "DEC", 0),		// 0x2D
            new InstructionReference("LD L, n8", "LD", 1),		// 0x2E
            new InstructionReference("CPL ", "CPL", 0),		// 0x2F
            new InstructionReference("JR NC, e8", "JR", 1),		// 0x30
            new InstructionReference("LD SP, n16", "LD", 2),		// 0x31
            new InstructionReference("LD HL, A", "LD", 0),		// 0x32
            new InstructionReference("INC SP", "INC", 0),		// 0x33
            new InstructionReference("INC HL", "INC", 0),		// 0x34
            new InstructionReference("DEC HL", "DEC", 0),		// 0x35
            new InstructionReference("LD HL, n8", "LD", 1),		// 0x36
            new InstructionReference("SCF ", "SCF", 0),		// 0x37
            new InstructionReference("JR C, e8", "JR", 1),		// 0x38
            new InstructionReference("ADD HL, SP", "ADD", 0),		// 0x39
            new InstructionReference("LD A, HL", "LD", 0),		// 0x3A
            new InstructionReference("DEC SP", "DEC", 0),		// 0x3B
            new InstructionReference("INC A", "INC", 0),		// 0x3C
            new InstructionReference("DEC A", "DEC", 0),		// 0x3D
            new InstructionReference("LD A, n8", "LD", 1),		// 0x3E
            new InstructionReference("CCF ", "CCF", 0),		// 0x3F
            new InstructionReference("LD B, B", "LD", 0),		// 0x40
            new InstructionReference("LD B, C", "LD", 0),		// 0x41
            new InstructionReference("LD B, D", "LD", 0),		// 0x42
            new InstructionReference("LD B, E", "LD", 0),		// 0x43
            new InstructionReference("LD B, H", "LD", 0),		// 0x44
            new InstructionReference("LD B, L", "LD", 0),		// 0x45
            new InstructionReference("LD B, HL", "LD", 0),		// 0x46
            new InstructionReference("LD B, A", "LD", 0),		// 0x47
            new InstructionReference("LD C, B", "LD", 0),		// 0x48
            new InstructionReference("LD C, C", "LD", 0),		// 0x49
            new InstructionReference("LD C, D", "LD", 0),		// 0x4A
            new InstructionReference("LD C, E", "LD", 0),		// 0x4B
            new InstructionReference("LD C, H", "LD", 0),		// 0x4C
            new InstructionReference("LD C, L", "LD", 0),		// 0x4D
            new InstructionReference("LD C, HL", "LD", 0),		// 0x4E
            new InstructionReference("LD C, A", "LD", 0),		// 0x4F
            new InstructionReference("LD D, B", "LD", 0),		// 0x50
            new InstructionReference("LD D, C", "LD", 0),		// 0x51
            new InstructionReference("LD D, D", "LD", 0),		// 0x52
            new InstructionReference("LD D, E", "LD", 0),		// 0x53
            new InstructionReference("LD D, H", "LD", 0),		// 0x54
            new InstructionReference("LD D, L", "LD", 0),		// 0x55
            new InstructionReference("LD D, HL", "LD", 0),		// 0x56
            new InstructionReference("LD D, A", "LD", 0),		// 0x57
            new InstructionReference("LD E, B", "LD", 0),		// 0x58
            new InstructionReference("LD E, C", "LD", 0),		// 0x59
            new InstructionReference("LD E, D", "LD", 0),		// 0x5A
            new InstructionReference("LD E, E", "LD", 0),		// 0x5B
            new InstructionReference("LD E, H", "LD", 0),		// 0x5C
            new InstructionReference("LD E, L", "LD", 0),		// 0x5D
            new InstructionReference("LD E, HL", "LD", 0),		// 0x5E
            new InstructionReference("LD E, A", "LD", 0),		// 0x5F
            new InstructionReference("LD H, B", "LD", 0),		// 0x60
            new InstructionReference("LD H, C", "LD", 0),		// 0x61
            new InstructionReference("LD H, D", "LD", 0),		// 0x62
            new InstructionReference("LD H, E", "LD", 0),		// 0x63
            new InstructionReference("LD H, H", "LD", 0),		// 0x64
            new InstructionReference("LD H, L", "LD", 0),		// 0x65
            new InstructionReference("LD H, HL", "LD", 0),		// 0x66
            new InstructionReference("LD H, A", "LD", 0),		// 0x67
            new InstructionReference("LD L, B", "LD", 0),		// 0x68
            new InstructionReference("LD L, C", "LD", 0),		// 0x69
            new InstructionReference("LD L, D", "LD", 0),		// 0x6A
            new InstructionReference("LD L, E", "LD", 0),		// 0x6B
            new InstructionReference("LD L, H", "LD", 0),		// 0x6C
            new InstructionReference("LD L, L", "LD", 0),		// 0x6D
            new InstructionReference("LD L, HL", "LD", 0),		// 0x6E
            new InstructionReference("LD L, A", "LD", 0),		// 0x6F
            new InstructionReference("LD HL, B", "LD", 0),		// 0x70
            new InstructionReference("LD HL, C", "LD", 0),		// 0x71
            new InstructionReference("LD HL, D", "LD", 0),		// 0x72
            new InstructionReference("LD HL, E", "LD", 0),		// 0x73
            new InstructionReference("LD HL, H", "LD", 0),		// 0x74
            new InstructionReference("LD HL, L", "LD", 0),		// 0x75
            new InstructionReference("HALT ", "HALT", 0),		// 0x76
            new InstructionReference("LD HL, A", "LD", 0),		// 0x77
            new InstructionReference("LD A, B", "LD", 0),		// 0x78
            new InstructionReference("LD A, C", "LD", 0),		// 0x79
            new InstructionReference("LD A, D", "LD", 0),		// 0x7A
            new InstructionReference("LD A, E", "LD", 0),		// 0x7B
            new InstructionReference("LD A, H", "LD", 0),		// 0x7C
            new InstructionReference("LD A, L", "LD", 0),		// 0x7D
            new InstructionReference("LD A, HL", "LD", 0),		// 0x7E
            new InstructionReference("LD A, A", "LD", 0),		// 0x7F
            new InstructionReference("ADD A, B", "ADD", 0),		// 0x80
            new InstructionReference("ADD A, C", "ADD", 0),		// 0x81
            new InstructionReference("ADD A, D", "ADD", 0),		// 0x82
            new InstructionReference("ADD A, E", "ADD", 0),		// 0x83
            new InstructionReference("ADD A, H", "ADD", 0),		// 0x84
            new InstructionReference("ADD A, L", "ADD", 0),		// 0x85
            new InstructionReference("ADD A, HL", "ADD", 0),		// 0x86
            new InstructionReference("ADD A, A", "ADD", 0),		// 0x87
            new InstructionReference("ADC A, B", "ADC", 0),		// 0x88
            new InstructionReference("ADC A, C", "ADC", 0),		// 0x89
            new InstructionReference("ADC A, D", "ADC", 0),		// 0x8A
            new InstructionReference("ADC A, E", "ADC", 0),		// 0x8B
            new InstructionReference("ADC A, H", "ADC", 0),		// 0x8C
            new InstructionReference("ADC A, L", "ADC", 0),		// 0x8D
            new InstructionReference("ADC A, HL", "ADC", 0),		// 0x8E
            new InstructionReference("ADC A, A", "ADC", 0),		// 0x8F
            new InstructionReference("SUB A, B", "SUB", 0),		// 0x90
            new InstructionReference("SUB A, C", "SUB", 0),		// 0x91
            new InstructionReference("SUB A, D", "SUB", 0),		// 0x92
            new InstructionReference("SUB A, E", "SUB", 0),		// 0x93
            new InstructionReference("SUB A, H", "SUB", 0),		// 0x94
            new InstructionReference("SUB A, L", "SUB", 0),		// 0x95
            new InstructionReference("SUB A, HL", "SUB", 0),		// 0x96
            new InstructionReference("SUB A, A", "SUB", 0),		// 0x97
            new InstructionReference("SBC A, B", "SBC", 0),		// 0x98
            new InstructionReference("SBC A, C", "SBC", 0),		// 0x99
            new InstructionReference("SBC A, D", "SBC", 0),		// 0x9A
            new InstructionReference("SBC A, E", "SBC", 0),		// 0x9B
            new InstructionReference("SBC A, H", "SBC", 0),		// 0x9C
            new InstructionReference("SBC A, L", "SBC", 0),		// 0x9D
            new InstructionReference("SBC A, HL", "SBC", 0),		// 0x9E
            new InstructionReference("SBC A, A", "SBC", 0),		// 0x9F
            new InstructionReference("AND A, B", "AND", 0),		// 0xA0
            new InstructionReference("AND A, C", "AND", 0),		// 0xA1
            new InstructionReference("AND A, D", "AND", 0),		// 0xA2
            new InstructionReference("AND A, E", "AND", 0),		// 0xA3
            new InstructionReference("AND A, H", "AND", 0),		// 0xA4
            new InstructionReference("AND A, L", "AND", 0),		// 0xA5
            new InstructionReference("AND A, HL", "AND", 0),		// 0xA6
            new InstructionReference("AND A, A", "AND", 0),		// 0xA7
            new InstructionReference("XOR A, B", "XOR", 0),		// 0xA8
            new InstructionReference("XOR A, C", "XOR", 0),		// 0xA9
            new InstructionReference("XOR A, D", "XOR", 0),		// 0xAA
            new InstructionReference("XOR A, E", "XOR", 0),		// 0xAB
            new InstructionReference("XOR A, H", "XOR", 0),		// 0xAC
            new InstructionReference("XOR A, L", "XOR", 0),		// 0xAD
            new InstructionReference("XOR A, HL", "XOR", 0),		// 0xAE
            new InstructionReference("XOR A, A", "XOR", 0),		// 0xAF
            new InstructionReference("OR A, B", "OR", 0),		// 0xB0
            new InstructionReference("OR A, C", "OR", 0),		// 0xB1
            new InstructionReference("OR A, D", "OR", 0),		// 0xB2
            new InstructionReference("OR A, E", "OR", 0),		// 0xB3
            new InstructionReference("OR A, H", "OR", 0),		// 0xB4
            new InstructionReference("OR A, L", "OR", 0),		// 0xB5
            new InstructionReference("OR A, HL", "OR", 0),		// 0xB6
            new InstructionReference("OR A, A", "OR", 0),		// 0xB7
            new InstructionReference("CP A, B", "CP", 0),		// 0xB8
            new InstructionReference("CP A, C", "CP", 0),		// 0xB9
            new InstructionReference("CP A, D", "CP", 0),		// 0xBA
            new InstructionReference("CP A, E", "CP", 0),		// 0xBB
            new InstructionReference("CP A, H", "CP", 0),		// 0xBC
            new InstructionReference("CP A, L", "CP", 0),		// 0xBD
            new InstructionReference("CP A, HL", "CP", 0),		// 0xBE
            new InstructionReference("CP A, A", "CP", 0),		// 0xBF
            new InstructionReference("RET NZ", "RET", 0),		// 0xC0
            new InstructionReference("POP BC", "POP", 0),		// 0xC1
            new InstructionReference("JP NZ, a16", "JP", 2),		// 0xC2
            new InstructionReference("JP a16", "JP", 2),		// 0xC3
            new InstructionReference("CALL NZ, a16", "CALL", 2),		// 0xC4
            new InstructionReference("PUSH BC", "PUSH", 0),		// 0xC5
            new InstructionReference("ADD A, n8", "ADD", 1),		// 0xC6
            new InstructionReference("RST $00", "RST", 0),		// 0xC7
            new InstructionReference("RET Z", "RET", 0),		// 0xC8
            new InstructionReference("RET ", "RET", 0),		// 0xC9
            new InstructionReference("JP Z, a16", "JP", 2),		// 0xCA
            new InstructionReference("PREFIX ", "PREFIX", 0),		// 0xCB
            new InstructionReference("CALL Z, a16", "CALL", 2),		// 0xCC
            new InstructionReference("CALL a16", "CALL", 2),		// 0xCD
            new InstructionReference("ADC A, n8", "ADC", 1),		// 0xCE
            new InstructionReference("RST $08", "RST", 0),		// 0xCF
            new InstructionReference("RET NC", "RET", 0),		// 0xD0
            new InstructionReference("POP DE", "POP", 0),		// 0xD1
            new InstructionReference("JP NC, a16", "JP", 2),		// 0xD2
            new InstructionReference("ILLEGAL_D3 ", "ILLEGAL_D3", 0),		// 0xD3
            new InstructionReference("CALL NC, a16", "CALL", 2),		// 0xD4
            new InstructionReference("PUSH DE", "PUSH", 0),		// 0xD5
            new InstructionReference("SUB A, n8", "SUB", 1),		// 0xD6
            new InstructionReference("RST $10", "RST", 0),		// 0xD7
            new InstructionReference("RET C", "RET", 0),		// 0xD8
            new InstructionReference("RETI ", "RETI", 0),		// 0xD9
            new InstructionReference("JP C, a16", "JP", 2),		// 0xDA
            new InstructionReference("ILLEGAL_DB ", "ILLEGAL_DB", 0),		// 0xDB
            new InstructionReference("CALL C, a16", "CALL", 2),		// 0xDC
            new InstructionReference("ILLEGAL_DD ", "ILLEGAL_DD", 0),		// 0xDD
            new InstructionReference("SBC A, n8", "SBC", 1),		// 0xDE
            new InstructionReference("RST $18", "RST", 0),		// 0xDF
            new InstructionReference("LDH a8, A", "LDH", 1),		// 0xE0
            new InstructionReference("POP HL", "POP", 0),		// 0xE1
            new InstructionReference("LD C, A", "LD", 0),		// 0xE2
            new InstructionReference("ILLEGAL_E3 ", "ILLEGAL_E3", 0),		// 0xE3
            new InstructionReference("ILLEGAL_E4 ", "ILLEGAL_E4", 0),		// 0xE4
            new InstructionReference("PUSH HL", "PUSH", 0),		// 0xE5
            new InstructionReference("AND A, n8", "AND", 1),		// 0xE6
            new InstructionReference("RST $20", "RST", 0),		// 0xE7
            new InstructionReference("ADD SP, e8", "ADD", 1),		// 0xE8
            new InstructionReference("JP HL", "JP", 0),		// 0xE9
            new InstructionReference("LD a16, A", "LD", 2),		// 0xEA
            new InstructionReference("ILLEGAL_EB ", "ILLEGAL_EB", 0),		// 0xEB
            new InstructionReference("ILLEGAL_EC ", "ILLEGAL_EC", 0),		// 0xEC
            new InstructionReference("ILLEGAL_ED ", "ILLEGAL_ED", 0),		// 0xED
            new InstructionReference("XOR A, n8", "XOR", 1),		// 0xEE
            new InstructionReference("RST $28", "RST", 0),		// 0xEF
            new InstructionReference("LDH A, a8", "LDH", 1),		// 0xF0
            new InstructionReference("POP AF", "POP", 0),		// 0xF1
            new InstructionReference("LD A, C", "LD", 0),		// 0xF2
            new InstructionReference("DI ", "DI", 0),		// 0xF3
            new InstructionReference("ILLEGAL_F4 ", "ILLEGAL_F4", 0),		// 0xF4
            new InstructionReference("PUSH AF", "PUSH", 0),		// 0xF5
            new InstructionReference("OR A, n8", "OR", 1),		// 0xF6
            new InstructionReference("RST $30", "RST", 0),		// 0xF7
            new InstructionReference("LD HL, SP, e8", "LD", 1),		// 0xF8
            new InstructionReference("LD SP, HL", "LD", 0),		// 0xF9
            new InstructionReference("LD A, a16", "LD", 2),		// 0xFA
            new InstructionReference("EI ", "EI", 0),		// 0xFB
            new InstructionReference("ILLEGAL_FC ", "ILLEGAL_FC", 0),		// 0xFC
            new InstructionReference("ILLEGAL_FD ", "ILLEGAL_FD", 0),		// 0xFD
            new InstructionReference("CP A, n8", "CP", 1),		// 0xFE
            new InstructionReference("RST $38", "RST", 0),		// 0xFF
            new InstructionReference("RLC B", "RLC", 1),		// 0x00
            new InstructionReference("RLC C", "RLC", 1),		// 0x01
            new InstructionReference("RLC D", "RLC", 1),		// 0x02
            new InstructionReference("RLC E", "RLC", 1),		// 0x03
            new InstructionReference("RLC H", "RLC", 1),		// 0x04
            new InstructionReference("RLC L", "RLC", 1),		// 0x05
            new InstructionReference("RLC HL", "RLC", 1),		// 0x06
            new InstructionReference("RLC A", "RLC", 1),		// 0x07
            new InstructionReference("RRC B", "RRC", 1),		// 0x08
            new InstructionReference("RRC C", "RRC", 1),		// 0x09
            new InstructionReference("RRC D", "RRC", 1),		// 0x0A
            new InstructionReference("RRC E", "RRC", 1),		// 0x0B
            new InstructionReference("RRC H", "RRC", 1),		// 0x0C
            new InstructionReference("RRC L", "RRC", 1),		// 0x0D
            new InstructionReference("RRC HL", "RRC", 1),		// 0x0E
            new InstructionReference("RRC A", "RRC", 1),		// 0x0F
            new InstructionReference("RL B", "RL", 1),		// 0x10
            new InstructionReference("RL C", "RL", 1),		// 0x11
            new InstructionReference("RL D", "RL", 1),		// 0x12
            new InstructionReference("RL E", "RL", 1),		// 0x13
            new InstructionReference("RL H", "RL", 1),		// 0x14
            new InstructionReference("RL L", "RL", 1),		// 0x15
            new InstructionReference("RL HL", "RL", 1),		// 0x16
            new InstructionReference("RL A", "RL", 1),		// 0x17
            new InstructionReference("RR B", "RR", 1),		// 0x18
            new InstructionReference("RR C", "RR", 1),		// 0x19
            new InstructionReference("RR D", "RR", 1),		// 0x1A
            new InstructionReference("RR E", "RR", 1),		// 0x1B
            new InstructionReference("RR H", "RR", 1),		// 0x1C
            new InstructionReference("RR L", "RR", 1),		// 0x1D
            new InstructionReference("RR HL", "RR", 1),		// 0x1E
            new InstructionReference("RR A", "RR", 1),		// 0x1F
            new InstructionReference("SLA B", "SLA", 1),		// 0x20
            new InstructionReference("SLA C", "SLA", 1),		// 0x21
            new InstructionReference("SLA D", "SLA", 1),		// 0x22
            new InstructionReference("SLA E", "SLA", 1),		// 0x23
            new InstructionReference("SLA H", "SLA", 1),		// 0x24
            new InstructionReference("SLA L", "SLA", 1),		// 0x25
            new InstructionReference("SLA HL", "SLA", 1),		// 0x26
            new InstructionReference("SLA A", "SLA", 1),		// 0x27
            new InstructionReference("SRA B", "SRA", 1),		// 0x28
            new InstructionReference("SRA C", "SRA", 1),		// 0x29
            new InstructionReference("SRA D", "SRA", 1),		// 0x2A
            new InstructionReference("SRA E", "SRA", 1),		// 0x2B
            new InstructionReference("SRA H", "SRA", 1),		// 0x2C
            new InstructionReference("SRA L", "SRA", 1),		// 0x2D
            new InstructionReference("SRA HL", "SRA", 1),		// 0x2E
            new InstructionReference("SRA A", "SRA", 1),		// 0x2F
            new InstructionReference("SWAP B", "SWAP", 1),		// 0x30
            new InstructionReference("SWAP C", "SWAP", 1),		// 0x31
            new InstructionReference("SWAP D", "SWAP", 1),		// 0x32
            new InstructionReference("SWAP E", "SWAP", 1),		// 0x33
            new InstructionReference("SWAP H", "SWAP", 1),		// 0x34
            new InstructionReference("SWAP L", "SWAP", 1),		// 0x35
            new InstructionReference("SWAP HL", "SWAP", 1),		// 0x36
            new InstructionReference("SWAP A", "SWAP", 1),		// 0x37
            new InstructionReference("SRL B", "SRL", 1),		// 0x38
            new InstructionReference("SRL C", "SRL", 1),		// 0x39
            new InstructionReference("SRL D", "SRL", 1),		// 0x3A
            new InstructionReference("SRL E", "SRL", 1),		// 0x3B
            new InstructionReference("SRL H", "SRL", 1),		// 0x3C
            new InstructionReference("SRL L", "SRL", 1),		// 0x3D
            new InstructionReference("SRL HL", "SRL", 1),		// 0x3E
            new InstructionReference("SRL A", "SRL", 1),		// 0x3F
            new InstructionReference("BIT 0, B", "BIT", 1),		// 0x40
            new InstructionReference("BIT 0, C", "BIT", 1),		// 0x41
            new InstructionReference("BIT 0, D", "BIT", 1),		// 0x42
            new InstructionReference("BIT 0, E", "BIT", 1),		// 0x43
            new InstructionReference("BIT 0, H", "BIT", 1),		// 0x44
            new InstructionReference("BIT 0, L", "BIT", 1),		// 0x45
            new InstructionReference("BIT 0, HL", "BIT", 1),		// 0x46
            new InstructionReference("BIT 0, A", "BIT", 1),		// 0x47
            new InstructionReference("BIT 1, B", "BIT", 1),		// 0x48
            new InstructionReference("BIT 1, C", "BIT", 1),		// 0x49
            new InstructionReference("BIT 1, D", "BIT", 1),		// 0x4A
            new InstructionReference("BIT 1, E", "BIT", 1),		// 0x4B
            new InstructionReference("BIT 1, H", "BIT", 1),		// 0x4C
            new InstructionReference("BIT 1, L", "BIT", 1),		// 0x4D
            new InstructionReference("BIT 1, HL", "BIT", 1),		// 0x4E
            new InstructionReference("BIT 1, A", "BIT", 1),		// 0x4F
            new InstructionReference("BIT 2, B", "BIT", 1),		// 0x50
            new InstructionReference("BIT 2, C", "BIT", 1),		// 0x51
            new InstructionReference("BIT 2, D", "BIT", 1),		// 0x52
            new InstructionReference("BIT 2, E", "BIT", 1),		// 0x53
            new InstructionReference("BIT 2, H", "BIT", 1),		// 0x54
            new InstructionReference("BIT 2, L", "BIT", 1),		// 0x55
            new InstructionReference("BIT 2, HL", "BIT", 1),		// 0x56
            new InstructionReference("BIT 2, A", "BIT", 1),		// 0x57
            new InstructionReference("BIT 3, B", "BIT", 1),		// 0x58
            new InstructionReference("BIT 3, C", "BIT", 1),		// 0x59
            new InstructionReference("BIT 3, D", "BIT", 1),		// 0x5A
            new InstructionReference("BIT 3, E", "BIT", 1),		// 0x5B
            new InstructionReference("BIT 3, H", "BIT", 1),		// 0x5C
            new InstructionReference("BIT 3, L", "BIT", 1),		// 0x5D
            new InstructionReference("BIT 3, HL", "BIT", 1),		// 0x5E
            new InstructionReference("BIT 3, A", "BIT", 1),		// 0x5F
            new InstructionReference("BIT 4, B", "BIT", 1),		// 0x60
            new InstructionReference("BIT 4, C", "BIT", 1),		// 0x61
            new InstructionReference("BIT 4, D", "BIT", 1),		// 0x62
            new InstructionReference("BIT 4, E", "BIT", 1),		// 0x63
            new InstructionReference("BIT 4, H", "BIT", 1),		// 0x64
            new InstructionReference("BIT 4, L", "BIT", 1),		// 0x65
            new InstructionReference("BIT 4, HL", "BIT", 1),		// 0x66
            new InstructionReference("BIT 4, A", "BIT", 1),		// 0x67
            new InstructionReference("BIT 5, B", "BIT", 1),		// 0x68
            new InstructionReference("BIT 5, C", "BIT", 1),		// 0x69
            new InstructionReference("BIT 5, D", "BIT", 1),		// 0x6A
            new InstructionReference("BIT 5, E", "BIT", 1),		// 0x6B
            new InstructionReference("BIT 5, H", "BIT", 1),		// 0x6C
            new InstructionReference("BIT 5, L", "BIT", 1),		// 0x6D
            new InstructionReference("BIT 5, HL", "BIT", 1),		// 0x6E
            new InstructionReference("BIT 5, A", "BIT", 1),		// 0x6F
            new InstructionReference("BIT 6, B", "BIT", 1),		// 0x70
            new InstructionReference("BIT 6, C", "BIT", 1),		// 0x71
            new InstructionReference("BIT 6, D", "BIT", 1),		// 0x72
            new InstructionReference("BIT 6, E", "BIT", 1),		// 0x73
            new InstructionReference("BIT 6, H", "BIT", 1),		// 0x74
            new InstructionReference("BIT 6, L", "BIT", 1),		// 0x75
            new InstructionReference("BIT 6, HL", "BIT", 1),		// 0x76
            new InstructionReference("BIT 6, A", "BIT", 1),		// 0x77
            new InstructionReference("BIT 7, B", "BIT", 1),		// 0x78
            new InstructionReference("BIT 7, C", "BIT", 1),		// 0x79
            new InstructionReference("BIT 7, D", "BIT", 1),		// 0x7A
            new InstructionReference("BIT 7, E", "BIT", 1),		// 0x7B
            new InstructionReference("BIT 7, H", "BIT", 1),		// 0x7C
            new InstructionReference("BIT 7, L", "BIT", 1),		// 0x7D
            new InstructionReference("BIT 7, HL", "BIT", 1),		// 0x7E
            new InstructionReference("BIT 7, A", "BIT", 1),		// 0x7F
            new InstructionReference("RES 0, B", "RES", 1),		// 0x80
            new InstructionReference("RES 0, C", "RES", 1),		// 0x81
            new InstructionReference("RES 0, D", "RES", 1),		// 0x82
            new InstructionReference("RES 0, E", "RES", 1),		// 0x83
            new InstructionReference("RES 0, H", "RES", 1),		// 0x84
            new InstructionReference("RES 0, L", "RES", 1),		// 0x85
            new InstructionReference("RES 0, HL", "RES", 1),		// 0x86
            new InstructionReference("RES 0, A", "RES", 1),		// 0x87
            new InstructionReference("RES 1, B", "RES", 1),		// 0x88
            new InstructionReference("RES 1, C", "RES", 1),		// 0x89
            new InstructionReference("RES 1, D", "RES", 1),		// 0x8A
            new InstructionReference("RES 1, E", "RES", 1),		// 0x8B
            new InstructionReference("RES 1, H", "RES", 1),		// 0x8C
            new InstructionReference("RES 1, L", "RES", 1),		// 0x8D
            new InstructionReference("RES 1, HL", "RES", 1),		// 0x8E
            new InstructionReference("RES 1, A", "RES", 1),		// 0x8F
            new InstructionReference("RES 2, B", "RES", 1),		// 0x90
            new InstructionReference("RES 2, C", "RES", 1),		// 0x91
            new InstructionReference("RES 2, D", "RES", 1),		// 0x92
            new InstructionReference("RES 2, E", "RES", 1),		// 0x93
            new InstructionReference("RES 2, H", "RES", 1),		// 0x94
            new InstructionReference("RES 2, L", "RES", 1),		// 0x95
            new InstructionReference("RES 2, HL", "RES", 1),		// 0x96
            new InstructionReference("RES 2, A", "RES", 1),		// 0x97
            new InstructionReference("RES 3, B", "RES", 1),		// 0x98
            new InstructionReference("RES 3, C", "RES", 1),		// 0x99
            new InstructionReference("RES 3, D", "RES", 1),		// 0x9A
            new InstructionReference("RES 3, E", "RES", 1),		// 0x9B
            new InstructionReference("RES 3, H", "RES", 1),		// 0x9C
            new InstructionReference("RES 3, L", "RES", 1),		// 0x9D
            new InstructionReference("RES 3, HL", "RES", 1),		// 0x9E
            new InstructionReference("RES 3, A", "RES", 1),		// 0x9F
            new InstructionReference("RES 4, B", "RES", 1),		// 0xA0
            new InstructionReference("RES 4, C", "RES", 1),		// 0xA1
            new InstructionReference("RES 4, D", "RES", 1),		// 0xA2
            new InstructionReference("RES 4, E", "RES", 1),		// 0xA3
            new InstructionReference("RES 4, H", "RES", 1),		// 0xA4
            new InstructionReference("RES 4, L", "RES", 1),		// 0xA5
            new InstructionReference("RES 4, HL", "RES", 1),		// 0xA6
            new InstructionReference("RES 4, A", "RES", 1),		// 0xA7
            new InstructionReference("RES 5, B", "RES", 1),		// 0xA8
            new InstructionReference("RES 5, C", "RES", 1),		// 0xA9
            new InstructionReference("RES 5, D", "RES", 1),		// 0xAA
            new InstructionReference("RES 5, E", "RES", 1),		// 0xAB
            new InstructionReference("RES 5, H", "RES", 1),		// 0xAC
            new InstructionReference("RES 5, L", "RES", 1),		// 0xAD
            new InstructionReference("RES 5, HL", "RES", 1),		// 0xAE
            new InstructionReference("RES 5, A", "RES", 1),		// 0xAF
            new InstructionReference("RES 6, B", "RES", 1),		// 0xB0
            new InstructionReference("RES 6, C", "RES", 1),		// 0xB1
            new InstructionReference("RES 6, D", "RES", 1),		// 0xB2
            new InstructionReference("RES 6, E", "RES", 1),		// 0xB3
            new InstructionReference("RES 6, H", "RES", 1),		// 0xB4
            new InstructionReference("RES 6, L", "RES", 1),		// 0xB5
            new InstructionReference("RES 6, HL", "RES", 1),		// 0xB6
            new InstructionReference("RES 6, A", "RES", 1),		// 0xB7
            new InstructionReference("RES 7, B", "RES", 1),		// 0xB8
            new InstructionReference("RES 7, C", "RES", 1),		// 0xB9
            new InstructionReference("RES 7, D", "RES", 1),		// 0xBA
            new InstructionReference("RES 7, E", "RES", 1),		// 0xBB
            new InstructionReference("RES 7, H", "RES", 1),		// 0xBC
            new InstructionReference("RES 7, L", "RES", 1),		// 0xBD
            new InstructionReference("RES 7, HL", "RES", 1),		// 0xBE
            new InstructionReference("RES 7, A", "RES", 1),		// 0xBF
            new InstructionReference("SET 0, B", "SET", 1),		// 0xC0
            new InstructionReference("SET 0, C", "SET", 1),		// 0xC1
            new InstructionReference("SET 0, D", "SET", 1),		// 0xC2
            new InstructionReference("SET 0, E", "SET", 1),		// 0xC3
            new InstructionReference("SET 0, H", "SET", 1),		// 0xC4
            new InstructionReference("SET 0, L", "SET", 1),		// 0xC5
            new InstructionReference("SET 0, HL", "SET", 1),		// 0xC6
            new InstructionReference("SET 0, A", "SET", 1),		// 0xC7
            new InstructionReference("SET 1, B", "SET", 1),		// 0xC8
            new InstructionReference("SET 1, C", "SET", 1),		// 0xC9
            new InstructionReference("SET 1, D", "SET", 1),		// 0xCA
            new InstructionReference("SET 1, E", "SET", 1),		// 0xCB
            new InstructionReference("SET 1, H", "SET", 1),		// 0xCC
            new InstructionReference("SET 1, L", "SET", 1),		// 0xCD
            new InstructionReference("SET 1, HL", "SET", 1),		// 0xCE
            new InstructionReference("SET 1, A", "SET", 1),		// 0xCF
            new InstructionReference("SET 2, B", "SET", 1),		// 0xD0
            new InstructionReference("SET 2, C", "SET", 1),		// 0xD1
            new InstructionReference("SET 2, D", "SET", 1),		// 0xD2
            new InstructionReference("SET 2, E", "SET", 1),		// 0xD3
            new InstructionReference("SET 2, H", "SET", 1),		// 0xD4
            new InstructionReference("SET 2, L", "SET", 1),		// 0xD5
            new InstructionReference("SET 2, HL", "SET", 1),		// 0xD6
            new InstructionReference("SET 2, A", "SET", 1),		// 0xD7
            new InstructionReference("SET 3, B", "SET", 1),		// 0xD8
            new InstructionReference("SET 3, C", "SET", 1),		// 0xD9
            new InstructionReference("SET 3, D", "SET", 1),		// 0xDA
            new InstructionReference("SET 3, E", "SET", 1),		// 0xDB
            new InstructionReference("SET 3, H", "SET", 1),		// 0xDC
            new InstructionReference("SET 3, L", "SET", 1),		// 0xDD
            new InstructionReference("SET 3, HL", "SET", 1),		// 0xDE
            new InstructionReference("SET 3, A", "SET", 1),		// 0xDF
            new InstructionReference("SET 4, B", "SET", 1),		// 0xE0
            new InstructionReference("SET 4, C", "SET", 1),		// 0xE1
            new InstructionReference("SET 4, D", "SET", 1),		// 0xE2
            new InstructionReference("SET 4, E", "SET", 1),		// 0xE3
            new InstructionReference("SET 4, H", "SET", 1),		// 0xE4
            new InstructionReference("SET 4, L", "SET", 1),		// 0xE5
            new InstructionReference("SET 4, HL", "SET", 1),		// 0xE6
            new InstructionReference("SET 4, A", "SET", 1),		// 0xE7
            new InstructionReference("SET 5, B", "SET", 1),		// 0xE8
            new InstructionReference("SET 5, C", "SET", 1),		// 0xE9
            new InstructionReference("SET 5, D", "SET", 1),		// 0xEA
            new InstructionReference("SET 5, E", "SET", 1),		// 0xEB
            new InstructionReference("SET 5, H", "SET", 1),		// 0xEC
            new InstructionReference("SET 5, L", "SET", 1),		// 0xED
            new InstructionReference("SET 5, HL", "SET", 1),		// 0xEE
            new InstructionReference("SET 5, A", "SET", 1),		// 0xEF
            new InstructionReference("SET 6, B", "SET", 1),		// 0xF0
            new InstructionReference("SET 6, C", "SET", 1),		// 0xF1
            new InstructionReference("SET 6, D", "SET", 1),		// 0xF2
            new InstructionReference("SET 6, E", "SET", 1),		// 0xF3
            new InstructionReference("SET 6, H", "SET", 1),		// 0xF4
            new InstructionReference("SET 6, L", "SET", 1),		// 0xF5
            new InstructionReference("SET 6, HL", "SET", 1),		// 0xF6
            new InstructionReference("SET 6, A", "SET", 1),		// 0xF7
            new InstructionReference("SET 7, B", "SET", 1),		// 0xF8
            new InstructionReference("SET 7, C", "SET", 1),		// 0xF9
            new InstructionReference("SET 7, D", "SET", 1),		// 0xFA
            new InstructionReference("SET 7, E", "SET", 1),		// 0xFB
            new InstructionReference("SET 7, H", "SET", 1),		// 0xFC
            new InstructionReference("SET 7, L", "SET", 1),		// 0xFD
            new InstructionReference("SET 7, HL", "SET", 1),		// 0xFE
            new InstructionReference("SET 7, A", "SET", 1),		// 0xFF
        };
    }
}
